# Site settings
title: Long Road Ahead
email:
description: "Some stuff I find interesting."
baseurl: ""
url: "http://letfoolsdie.github.io"
twitter_username: letfoolsdie
github_username:  letfoolsdie

# Build settings
markdown: redcarpet
permalink: pretty
