# Site settings
title: 
email:
description: ""
baseurl: ""
url: "http://letfoolsdie.github.io"
twitter_username: letfoolsdie
github_username:  letfoolsdie

# Build settings
markdown: redcarpet
permalink: pretty
